from typing import List, Dict, Any
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.core.dependencies import require_role
from app.db.models.user import User
from app.db.models.teacher import TeacherAlert
from app.schemas.teacher import (
    TeacherDashboardOut, StudentSummaryOut, TopicGapOut,
    TeacherAlertOut, AlertUpdate
)
from app.services.teacher_service import (
    get_teacher_dashboard, get_all_students_summary, get_student_detail_for_teacher
)

router = APIRouter(prefix="/teacher", tags=["Teacher"])

@router.get("/dashboard", response_model=TeacherDashboardOut)
def read_teacher_dashboard(
    current_user: User = Depends(require_role(["TEACHER", "ADMIN"])),
    db: Session = Depends(get_db)
):
    """Retrieve full teacher dashboard overview."""
    return get_teacher_dashboard(db)

@router.get("/students", response_model=List[StudentSummaryOut])
def list_students(
    current_user: User = Depends(require_role(["TEACHER", "ADMIN"])),
    db: Session = Depends(get_db)
):
    """Retrieve all students with academic risk markers and mastery metrics."""
    return get_all_students_summary(db)

@router.get("/students/{student_id}")
def inspect_student(
    student_id: int,
    current_user: User = Depends(require_role(["TEACHER", "ADMIN"])),
    db: Session = Depends(get_db)
):
    """Inspect detailed learning history, weak topics, and quiz attempts for a specific student."""
    data = get_student_detail_for_teacher(db, student_id)
    if not data:
        raise HTTPException(status_code=404, detail="Student not found")
    return data

@router.get("/performance")
def get_class_performance(
    current_user: User = Depends(require_role(["TEACHER", "ADMIN"])),
    db: Session = Depends(get_db)
):
    """Retrieve class-wide distribution and completion rates."""
    dash = get_teacher_dashboard(db)
    return {
        "average_class_performance": dash.average_class_performance,
        "completion_rate": dash.completion_rate,
        "total_students": dash.total_students,
        "students_needing_attention": dash.students_needing_attention
    }

@router.get("/topic-gaps", response_model=List[TopicGapOut])
def get_topic_gaps(
    current_user: User = Depends(require_role(["TEACHER", "ADMIN"])),
    db: Session = Depends(get_db)
):
    """Class-wide topic gap analytics sorted by areas needing highest intervention."""
    dash = get_teacher_dashboard(db)
    return dash.topic_gaps

@router.get("/alerts", response_model=List[TeacherAlertOut])
def list_alerts(
    current_user: User = Depends(require_role(["TEACHER", "ADMIN"])),
    db: Session = Depends(get_db)
):
    """List student risk alerts generated by the analytics engine."""
    dash = get_teacher_dashboard(db)
    return dash.recent_alerts

@router.patch("/alerts/{id}", response_model=TeacherAlertOut)
def update_alert(
    id: int,
    alert_update: AlertUpdate,
    current_user: User = Depends(require_role(["TEACHER", "ADMIN"])),
    db: Session = Depends(get_db)
):
    """Update status of a teacher alert (e.g. REVIEWED or RESOLVED)."""
    alert = db.query(TeacherAlert).filter(TeacherAlert.id == id).first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    alert.status = alert_update.status
    db.commit()
    db.refresh(alert)

    # Return full alert schema
    stu_name = alert.student.user.name if alert.student and alert.student.user else "Student"
    top_name = alert.topic.name if alert.topic else "Topic"
    return TeacherAlertOut(
        id=alert.id,
        student_id=alert.student_id,
        student_name=stu_name,
        topic_id=alert.topic_id,
        topic_name=top_name,
        alert_type=alert.alert_type,
        severity=alert.severity,
        message=alert.message,
        status=alert.status,
        created_at=alert.created_at
    )
