"use client";

import React from "react";
import Link from "next/link";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { recommendationService, Recommendation } from "@/services/recommendation.service";
import { RoleLayout } from "@/components/layout/RoleLayout";
import { Badge } from "@/components/common/Badge";
import {
  Lightbulb,
  CheckCircle2,
  PlayCircle,
  Sparkles,
  Loader2,
  AlertCircle,
  RefreshCw
} from "lucide-react";

export default function StudentRecommendationsPage() {
  const queryClient = useQueryClient();

  const {
    data,
    isLoading,
    error,
    refetch,
    isFetching
  } = useQuery<Recommendation[]>({
    queryKey: ["recommendations"],
    queryFn: recommendationService.getRecommendations,
  });

  const rawRecs = data as any;
  const recommendations: Recommendation[] = Array.isArray(rawRecs)
    ? rawRecs
    : Array.isArray(rawRecs?.recommendations)
    ? rawRecs.recommendations
    : Array.isArray(rawRecs?.data)
    ? rawRecs.data
    : [];

  const completeMutation = useMutation({
    mutationFn: (id: number) => recommendationService.completeRecommendation(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["recommendations"] });
      queryClient.invalidateQueries({ queryKey: ["studentDashboard"] });
    },
  });

  const generateMutation = useMutation({
    mutationFn: recommendationService.generateRecommendations,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["recommendations"] });
      queryClient.invalidateQueries({ queryKey: ["studentDashboard"] });
    },
  });

  return (
    <RoleLayout allowedRoles={["STUDENT", "ADMIN"]}>
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900">Personalized Recommendations</h1>
            <p className="mt-1 text-sm text-slate-500">
              Generated by the SPECTRA rules engine based on your mastery scores and diagnostic results.
            </p>
          </div>

          <div className="flex items-center gap-2 self-start sm:self-center">
            <button
              onClick={() => refetch()}
              disabled={isFetching}
              className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 shadow-sm hover:bg-slate-50 disabled:opacity-50"
            >
              <RefreshCw className={`h-3.5 w-3.5 text-slate-500 ${isFetching ? "animate-spin" : ""}`} />
              <span>Refresh</span>
            </button>

            <button
              onClick={() => generateMutation.mutate()}
              disabled={generateMutation.isPending}
              className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2 text-xs font-bold text-white shadow hover:bg-brand-700 disabled:opacity-50"
            >
              {generateMutation.isPending ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="h-4 w-4" />
              )}
              <span>Re-evaluate Learning Path</span>
            </button>
          </div>
        </div>

        {/* Loading State */}
        {isLoading ? (
          <div className="space-y-4 animate-pulse">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-32 bg-slate-200 rounded-2xl" />
            ))}
          </div>
        ) : error ? (
          <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-center text-rose-700">
            <AlertCircle className="h-8 w-8 mx-auto mb-2 text-rose-600" />
            <h3 className="font-bold text-sm">Failed to load recommendations</h3>
            <p className="text-xs text-rose-600 mt-1">{(error as any)?.message || "Please try again."}</p>
            <button
              onClick={() => refetch()}
              className="mt-4 inline-flex items-center gap-1.5 rounded-xl bg-rose-600 px-4 py-2 text-xs font-semibold text-white shadow hover:bg-rose-700"
            >
              <RefreshCw className="h-3.5 w-3.5" />
              <span>Retry</span>
            </button>
          </div>
        ) : recommendations.length > 0 ? (
          <div className="space-y-4">
            {recommendations.map((rec) => (
              <div
                key={rec.id}
                className="flex flex-col md:flex-row md:items-center justify-between gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm hover:border-brand-200 hover:shadow-md transition"
              >
                <div className="flex items-start gap-4">
                  <div className={`mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl ${
                    rec.priority === "HIGH" ? "bg-rose-50 text-rose-600" : "bg-brand-50 text-brand-600"
                  }`}>
                    <Lightbulb className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-[11px] font-bold uppercase text-slate-400">
                        {rec.subject_name || "General"} &bull; {rec.topic_name || "Foundations"}
                      </span>
                      <Badge
                        variant={rec.priority === "HIGH" ? "rose" : rec.priority === "MEDIUM" ? "amber" : "slate"}
                        size="sm"
                      >
                        {rec.priority} Priority
                      </Badge>
                    </div>

                    <h3 className="text-base font-bold text-slate-900 mt-1">{rec.title}</h3>
                    <p className="text-xs text-slate-600 mt-1.5 leading-relaxed max-w-2xl">
                      {rec.reason}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-3 self-end md:self-center shrink-0">
                  <button
                    onClick={() => completeMutation.mutate(rec.id)}
                    disabled={completeMutation.isPending}
                    className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 transition"
                  >
                    <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                    <span>Done</span>
                  </button>

                  <Link
                    href={rec.resource_id ? `/student/lessons/${rec.resource_id}` : "/student/quizzes/1"}
                    className="inline-flex items-center gap-1.5 rounded-xl bg-brand-600 px-4 py-2 text-xs font-bold text-white shadow hover:bg-brand-700 transition"
                  >
                    <PlayCircle className="h-4 w-4" />
                    <span>Start Practice</span>
                  </Link>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center">
            <CheckCircle2 className="h-8 w-8 text-emerald-600 mx-auto mb-2" />
            <h3 className="font-bold text-slate-900">All recommendations completed!</h3>
            <p className="text-xs text-slate-500 mt-1">Take a new quiz assessment to generate updated recommendations.</p>
            <Link
              href="/student/quizzes"
              className="mt-4 inline-block rounded-xl bg-brand-600 px-4 py-2 text-xs font-semibold text-white shadow"
            >
              Take Quiz
            </Link>
          </div>
        )}
      </div>
    </RoleLayout>
  );
}
